import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ConfigProvider, theme } from 'antd'

import AntdRegistry from '@/lib/Antd/AntdRegistry'
import LeftMenu from '@/components/LeftMenu'

import '@/styles/globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AntdRegistry>
          <ConfigProvider theme={{
            algorithm: theme.defaultAlgorithm,
            token: {
              fontFamily: 'inherit'
            }
          }}>
            <div className='w-full h-screen flex'>
              <div className='px-2 py-2 border-r'>
                <LeftMenu />
              </div>
              <div className='w-full px-5 py-5'>
                {children}
              </div>
            </div>
          </ConfigProvider>
        </AntdRegistry>
      </body>
    </html>
  )
}
